name: pfam_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - backcall=0.2.0
  - biopython=1.78
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.5
  - cryptography=38.0.1
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=11.8.86
  - cuda-documentation=11.8.86
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=11.8.87
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - freetype=2.10.4
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.4.7
  - jupyter_core=4.11.2
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.8
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nest-asyncio=1.5.5
  - nsight-compute=2022.3.0.22
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1s
  - packaging=21.3
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.7.15
  - python-dateutil=2.8.2
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pywin32=302
  - pyzmq=23.2.0
  - requests=2.28.1
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.39.3
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.1.1
  - typing_extensions=4.3.0
  - urllib3=1.26.12
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==22.1.0
    - bokeh==2.4.3
    - cachetools==5.2.0
    - click==8.0.4
    - distlib==0.3.6
    - fair-esm==0.4.0
    - filelock==3.8.0
    - fire==0.4.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.0
    - huggingface-hub==0.0.12
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - joblib==1.2.0
    - jsonschema==4.17.0
    - lightning-utilities==0.3.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - msgpack==1.0.4
    - multidict==6.0.2
    - oauthlib==3.2.2
    - pandas==1.3.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.4
    - protobuf==3.20.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyrsistent==0.19.2
    - pytorch-lightning==1.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - ray==2.1.0
    - regex==2022.10.31
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - sacremoses==0.0.53
    - seaborn==0.12.1
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.1.1
    - tokenizers==0.10.1
    - torch==1.13.0
    - torchaudio==0.13.0
    - torchmetrics==0.10.3
    - torchvision==0.14.0
    - tqdm==4.64.1
    - transformers==4.8.0
    - typish==1.9.3
    - virtualenv==20.16.7
    - wasabi==0.10.1
    - werkzeug==2.2.2
    - yarl==1.8.1
    - zipp==3.10.0
